package com.jewelry.pos.service;

import com.jewelry.pos.domain.entity.OldGoldPurchase;
import com.jewelry.pos.domain.entity.KaratEnum;
import com.jewelry.pos.domain.entity.PurityEnum;
import com.jewelry.pos.domain.entity.PurityEnumKaratConverter;
import com.jewelry.pos.domain.entity.ScrapInventory;
import com.jewelry.pos.domain.entity.ScrapPurification;
import com.jewelry.pos.domain.repository.OldGoldPurchaseRepository;
import com.jewelry.pos.domain.repository.ScrapInventoryRepository;
import com.jewelry.pos.domain.repository.ScrapPurificationRepository;
import com.jewelry.pos.web.dto.OldGoldRequestDTO;
import com.jewelry.pos.web.dto.PurificationRequestDTO;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
public class OldGoldService {

    private final OldGoldPurchaseRepository purchaseRepository;
    private final ScrapInventoryRepository scrapRepository;
    private final ScrapPurificationRepository purificationRepository;

    // --- 1. BUY LOGIC (Add to Scrap Box) ---
    @Transactional
    public BigDecimal processOldGoldPurchase(OldGoldRequestDTO request, String linkedSaleId) {
        // A. Calculate Value
        BigDecimal totalValue = request.weight().multiply(request.buyRate());

        // B. Create Record
        OldGoldPurchase purchase = new OldGoldPurchase();
        // ID is generated by @Tsid annotation or Database strategy
        purchase.setTransactionDate(LocalDateTime.now());
        purchase.setPurity(request.purity());
        purchase.setWeight(request.weight());
        purchase.setBuyRate(request.buyRate());
        purchase.setTotalValue(totalValue);
        purchase.setSaleId(linkedSaleId);
        purchase.setCustomerNationalId(request.customerNationalId());
        purchase.setCustomerPhoneNumber(request.customerPhoneNumber());
        purchase.setDescription(request.description());

        // Note: createdBy and createdDate are handled by @Auditable

        purchaseRepository.save(purchase);

        // C. Update Scrap Inventory (Increase Weight)
        addToScrapInventory(request.purity(), request.weight());

        return totalValue;
    }

    // --- 2. PURIFICATION LOGIC (Remove from Scrap Box) ---
    @Transactional
    public void processPurification(PurificationRequestDTO request) {
        PurityEnum purityEnum = new PurityEnumKaratConverter().convertToEntityAttribute(request.purity());
        KaratEnum karatEnum = KaratEnum.valueOf(new PurityEnumKaratConverter().convertToDatabaseColumn(purityEnum));

        // A. Check Availability
        ScrapInventory inventory = scrapRepository.findById(karatEnum)
                .orElseThrow(() -> new IllegalArgumentException("No scrap record found for " + request.purity()));

        if (inventory.getTotalWeight().compareTo(request.weightToSell()) < 0) {
            throw new IllegalStateException("Not enough scrap! Available: " + inventory.getTotalWeight() + "g");
        }

        // B. Deduct Weight
        inventory.setTotalWeight(inventory.getTotalWeight().subtract(request.weightToSell()));
        scrapRepository.save(inventory);

        // C. Log Transaction
        ScrapPurification purification = new ScrapPurification();
        purification.setTransactionDate(LocalDateTime.now());
        purification.setPurity(karatEnum);
        purification.setWeightOut(request.weightToSell());
        purification.setCashReceived(request.cashReceived());
        purification.setFactoryName(request.factoryName());

        purificationRepository.save(purification);
    }

    // Helper: Safely add weight to inventory
    private void addToScrapInventory(PurityEnum purity, BigDecimal weight) {
        KaratEnum karatEnum = KaratEnum.valueOf(new PurityEnumKaratConverter().convertToDatabaseColumn(purity));
        ScrapInventory inventory = scrapRepository.findById(karatEnum)
                .orElse(new ScrapInventory(karatEnum, BigDecimal.ZERO));

        inventory.setTotalWeight(inventory.getTotalWeight().add(weight));
        scrapRepository.save(inventory);
    }

    // Get current scrap inventory for dashboard
    @Transactional(readOnly = true)
    public List<ScrapInventory> getScrapInventory() {
        return scrapRepository.findAll();
    }
}